# Generated by Django 5.1.6 on 2025-03-10 20:47

import apps.media_files.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'file',
                    models.FileField(upload_to=apps.media_files.models.get_upload_path),
                ),
                ('name', models.CharField(blank=True, max_length=255)),
                (
                    'type',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('image', 'Image'),
                            ('video', 'Video'),
                            ('audio', 'Audio'),
                        ],
                        max_length=10,
                    ),
                ),
                ('size', models.PositiveIntegerField(blank=True)),
                (
                    'width',
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    'height',
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    'post',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='media_files',
                        to='content.post',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
            },
        ),
    ]
