# Generated by Django 5.1.6 on 2025-03-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='height',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='width',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
