# Generated by Django 5.1.6 on 2025-07-01 20:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0003_alter_category_description_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
