# Generated by Django 5.1.6 on 2025-07-01 20:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0004_alter_post_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('author', 'slug')},
        ),
    ]
