# Generated by Django 5.1.6 on 2025-08-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0005_alter_post_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
