# Generated by Django 5.1.6 on 2025-08-08 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorprofile',
            name='profile_picture',
        ),
    ]
