# Generated by Django 5.1.6 on 2025-05-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='bio',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authorprofile',
            name='profile_picture',
            field=models.ImageField(
                blank=True, null=True, upload_to='storage/profiles/'
            ),
        ),
    ]
